export const CLOTHES_MAPPING = {
    sit: {
        C_001: '/svg/equipments/clothes/sit/1.svg',
        C_002: '/svg/equipments/clothes/sit/2.svg',
        C_003: '/svg/equipments/clothes/sit/3.svg',
        C_004: '/svg/equipments/clothes/sit/4.svg',
        C_005: '/svg/equipments/clothes/sit/5.svg',
        C_006: '/svg/equipments/clothes/sit/6.svg',
        C_007: '/svg/equipments/clothes/sit/7.svg',
        C_008: '/svg/equipments/clothes/sit/8.svg',
        C_009: '/svg/equipments/clothes/sit/9.svg',
        C_010: '/svg/equipments/clothes/sit/10.svg',
        C_011: '/svg/equipments/clothes/sit/11.svg',
        C_012: '/svg/equipments/clothes/sit/12.svg',
        C_013: '/svg/equipments/clothes/sit/13.svg',
        C_014: '/svg/equipments/clothes/sit/14.svg',
    },
    stand: {
        C_001: '/svg/equipments/clothes/stand/1.svg',
        C_002: '/svg/equipments/clothes/stand/2.svg',
        C_003: '/svg/equipments/clothes/stand/3.svg',
        C_004: '/svg/equipments/clothes/stand/4.svg',
        C_005: '/svg/equipments/clothes/stand/5.svg',
        C_006: '/svg/equipments/clothes/stand/6.svg',
        C_007: '/svg/equipments/clothes/stand/7.svg',
        C_008: '/svg/equipments/clothes/stand/8.svg',
        C_009: '/svg/equipments/clothes/stand/9.svg',
        C_010: '/svg/equipments/clothes/stand/10.svg',
        C_011: '/svg/equipments/clothes/stand/11.svg',
        C_012: '/svg/equipments/clothes/stand/12.svg',
        C_013: '/svg/equipments/clothes/stand/13.svg',
        C_014: '/svg/equipments/clothes/stand/14.svg',
    }
}