export const CLOTHES_MAPPING = {
    // sit: {
    //     C_001: '/svg/equipments/clothes/sit/1.svg',
    //     C_002: '/svg/equipments/clothes/sit/2.svg',
    //     C_003: '/svg/equipments/clothes/sit/3.svg',
    //     C_004: '/svg/equipments/clothes/sit/4.svg',
    //     C_005: '/svg/equipments/clothes/sit/5.svg',
    //     C_006: '/svg/equipments/clothes/sit/6.svg',
    //     C_007: '/svg/equipments/clothes/sit/7.svg',
    //     C_008: '/svg/equipments/clothes/sit/8.svg',
    //     C_009: '/svg/equipments/clothes/sit/9.svg',
    //     C_010: '/svg/equipments/clothes/sit/10.svg',
    //     C_011: '/svg/equipments/clothes/sit/11.svg',
    //     C_012: '/svg/equipments/clothes/sit/12.svg',
    //     C_013: '/svg/equipments/clothes/sit/13.svg',
    //     C_014: '/svg/equipments/clothes/sit/14.svg',
    // },
    stand: {
        C_001: '/svg/equipments/clothes/stand/1.svg',
        C_002: '/svg/equipments/clothes/stand/2.svg',
        C_003: '/svg/equipments/clothes/stand/3.svg',
        C_004: '/svg/equipments/clothes/stand/4.svg',
        C_005: '/svg/equipments/clothes/stand/5.svg',
        C_006: '/svg/equipments/clothes/stand/6.svg',
        C_007: '/svg/equipments/clothes/stand/7.svg',
        C_008: '/svg/equipments/clothes/stand/8.svg',
        C_009: '/svg/equipments/clothes/stand/9.svg',
        C_010: '/svg/equipments/clothes/stand/10.svg',
        C_011: '/svg/equipments/clothes/stand/11.svg',
        C_012: '/svg/equipments/clothes/stand/12.svg',
        C_013: '/svg/equipments/clothes/stand/13.svg',
        C_014: '/svg/equipments/clothes/stand/14.svg',
        C_015: '/svg/equipments/clothes/stand/15.svg',
        C_016: '/svg/equipments/clothes/stand/16.svg',
        C_017: '/svg/equipments/clothes/stand/17.svg',
        C_018: '/svg/equipments/clothes/stand/18.svg',
        C_019: '/svg/equipments/clothes/stand/19.svg',
        C_020: '/svg/equipments/clothes/stand/20.svg',
        C_021: '/svg/equipments/clothes/stand/21.svg',
        C_022: '/svg/equipments/clothes/stand/22.svg',
        C_023: '/svg/equipments/clothes/stand/23.svg',
        C_024: '/svg/equipments/clothes/stand/24.svg',
        C_025: '/svg/equipments/clothes/stand/25.svg',
        C_026: '/svg/equipments/clothes/stand/26.svg',
        C_027: '/svg/equipments/clothes/stand/27.svg',
        C_028: '/svg/equipments/clothes/stand/28.svg',
        C_029: '/svg/equipments/clothes/stand/29.svg',
        C_030: '/svg/equipments/clothes/stand/30.svg',
        C_031: '/svg/equipments/clothes/stand/31.svg',
        C_032: '/svg/equipments/clothes/stand/32.svg'
    }
}